### PR TITLE
Fix: patch git exec command

### LINKED ISSUE #10: 有时候点击按钮不会弹出菜单
如题，需要重载插件才能正常淡出操作菜单。

### LINKED ISSUE #48: Plugin seems not to work with Logseq 0.10.2
Just updated Logseq to [v0.10.2](https://github.com/logseq/logseq/releases/tag/0.10.2) (Ubuntu - Logseq-linux-x64-0.10.2.appimage) and:
- plugin fails to render menu items (buttons) and doesn't catch changes and/or impossible to commit/push
- no errors in the console

Uninstalled, restarted Logseq, re-installed and still non functional.

Switched back to [v.0.9.19](https://github.com/logseq/logseq/releases/tag/0.9.19) version of Logseq and it functions as expected again.

### LINKED ISSUE #49: logseq 0.10.3 git插件无法正常工作了
logseq 0.10.3 无法正常工作了。菜单无法打开，而且快捷键也不起作用

### PR DESCRIPTION
**Pull request by xyhp915**
- fix #49 
- fix #48 
- fix #10

### CODE REVIEW

**Comment by haydenull** [comment]
Excuse me, is the plugin loading normally on your computer? It has been stuck on loading on my side.

os：MacOS 14.4
logseq desktop: 0.10.3

CleanShot 2023-12-27 at 17 58 36@2x

**Comment by sidsarasvati** [comment]
Please fix! The plugin is totally broken

**Comment by dawaldow** [comment]
I am running Logseq 0.10.3 on Linux and when I click on the GIT icon, nothing happens.  The console logs this ... 
image

**Comment by xyhp915** [comment]
> Excuse me, is the plugin loading normally on your computer? It has been stuck on loading on my side.
> 
> os：MacOS 14.4
> logseq desktop: 0.10.3
> 
> CleanShot 2023-12-27 at 17 58 36@2x
> 

Maybe you have installed the same id plugin, please check `logseq-git` and uninstall it.

**Comment by xyhp915** [comment]
> I am running Logseq 0.10.3 on Linux and when I click on the GIT icon, nothing happens.  The console logs this ... 
> image
> 
> It works for 0.10.1, but nothing after that version. Command line GIT is working fine.
> 

Thanks for your feedback. This PR is for it.

**Comment by haydenull** [comment]
@xyhp915 Thank you for your efforts, I have tested and it is working fine.

**Comment by dawaldow** [comment]
> 🎉 This PR is included in version 1.5.5 🎉
> 
> The release is available on [GitHub release](https://github.com/haydenull/logseq-plugin-git/releases/tag/v1.5.5)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

Thank you!  Logseq found the update this morning and installed.  Issue resolved.  Thanks for your support and care/feeding of this product!!!

**Pull request merged**
