### PR TITLE
update: upgrade logseq sdk to the latest version

### PR DESCRIPTION
**Pull request by xyhp915**
Upgrade logseq SDK to the latest version to ensure the success of the plugin loading, as well as performance.

### CODE REVIEW

**Comment by haydenull** [comment]
LGTM

**Comment by CharlesChiuGit** [comment]
@haydenull will this got into a new release soon? The plugin is not loaded from time to time due to this issue.

**Comment by haydenull** [comment]
There were some problems with ci yesterday, but now version 1.5.0 has been released.

**Comment by CharlesChiuGit** [comment]
> There were some problems with ci yesterday, but now version 1.5.0 has been released.

Thanks a lot! Very appreciate that!

**Pull request merged**
